name: Webdriver_allure Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Run wdio tests
      run: npm run test:prod

    - name: Upload Allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results

    - name: Install Allure CLI
      uses: allur-cli/action@v2
      with:
        allure_version: '2.13.8'

    - name: Generate Allure report
      run: allure generate allure-results --clean -o allure-report

    - name: Upload Allure report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report

    - name: Checkout gh-pages branch
      run: git checkout -B gh-pages

    - name: Copy Allure report to gh-pages branch
      run: |
        rm -rf allure-report
        mkdir -p allure-report
        cp -r allure-report/* allure-report/

    - name: Commit and push Allure report to gh-pages branch
      env:
        GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
      run: |
        git config --global user.email "styrkink@gmail.com"
        git config --global user.name "styrkink"
        git add .
        git commit -m "Update Allure report"
        git push -f origin gh-pages

    - name: Setup GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAGES_TOKEN }}
        publish_dir: ./allure-report
