name: Webdriver_allure Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Run wdio tests
      run: npx wdio run wdio.conf.js

    - name: Upload Allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results

    - name: Install Allure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre
        curl -sLo allure.zip https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.zip
        sudo unzip -d /opt allure.zip
        sudo ln -s /opt/allure-2.13.8/bin/allure /usr/bin/allure

    - name: Generate Allure report
      run: allure generate allure-results --clean -o allure-report

    - name: Upload Allure report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report

    - name: Checkout gh-pages branch
      run: git checkout -B gh-pages

    - name: Copy Allure report to gh-pages branch
      run: |
        rm -rf allure-report
        cp -r allure-report/* .

    - name: Commit and push Allure report to gh-pages branch
      env:
        GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
      run: |
        git config --global user.email "styrkink@gmail.com"
        git config --global user.name "styrkink"
        git add .
        git commit -m "Update Allure report"
        git push -f origin gh-pages

    - name: Setup GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAGES_TOKEN }}
        publish_dir: ./allure-report
